module.exports = {
  bookingMessages: {
    newBookingCreatedByUser: 'New ride is created.',
    cancelEventBookingCreatedByUser: 'Event booking canceled by User.',
    editEventBookingCreatedByUser: 'User edit event booking.',
    cancelEventBookingCreatedByAdmin: 'Event booking canceled by admin.',
    editEventBookingCreatedByUser: 'Admin edit event booking.',
    canceledBookingByUser: 'Ride canceled by customer.',
    newBookingNotification: 'You have new ride request.',
    bookingNotificationForsingleTrip: 'Do you want to join this ride as a co-driver.',
    askTopairedDriver: 'You have new pairing request.',
    pired: 'You are paired successfully.',
    unPaired: 'You are unpaired successfully.',
    tripAccepted: 'You ride is accepted.',
    tripStarted: 'Driver has started the ride.',
    tripCanceled: 'Driver has cancel the ride.',
    tripCompleted: 'Thank you for allowing Wingmen to have your back!',
    tripOngoing: 'Driver is on the way.',
    tripArrived: 'Driver has arrived.',
    adminAcceptEventBooking: 'Admin has accepted the booking.',
    adminCanceledEventBooking: 'Admin has reject the booking.',
    adminCompletedEventBooking: 'Admin has completed the booking.',
    tripAcceptedByAdmin: 'You ride is accepted.',
    tripAcceptedByAdminAssignYou: 'You ride is accepted by admin and assigning you.',
    tripStatusChange: 'Ride status changed.',
    noDriverAvailabeltripCanceled: 'No driver available.',
    autoAllocationStart: "Auto allocation start.",
    wingMenTitle: "My Wingmen"
  },
  eventType: {
    autoAllocationStart: 'AUTO_ALLOCATION_START',
    cancelEventBookingCreatedByUser: 'CANCEL_EVENT_BOOKING_BY_USER',
    editEventBookingCreatedByUser: 'EDIT_EVENT_BOOKING_BY_USER',
    cancelEventBookingCreatedByAdmin: 'CANCEL_EVENT_BOOKING_BY_ADMIN',
    editEventBookingCreatedByAdmin: 'EDIT_EVENT_BOOKING_BY_ADMIN',
    pairedNotification: 'PAIRED_NOTIFICATION',
    pairedSuccessfullyNotification: 'PAIRED_SUCCESSFULLY_NOTIFICATION',
    unPairedNotification: 'UN_PAIRED_NOTIFICATION',
    newBookingNotificationSendToDriver: 'NEW_BOOKING_NOTIFICATION_SEND_TO_DRIVER',
    newBookingNotificationSendToCoDriver: 'NEW_BOOKING_NOTIFICATION_SEND_TO_CO_DRIVER',
    bookingNotificationSendToDriverForsingleTrip: 'BOOKING_NOTIFICATION_SEND_TO_DRIVER_FOR_SINGLE_TRIP',
    driverAcceptBooking: 'DRIVER_ACCEPT_BOOKING_NOTIFICATION',
    driverStartBooking: 'DRIVER_START_BOOKING_NOTIFICATION',
    driverOngoingBooking: 'DRIVER_ONGOING_BOOKING_NOTIFICATION',
    driverArrivedBooking: 'DRIVER_ARRIVED_BOOKING_NOTIFICATION',
    driverCompletedBooking: 'DRIVER_COMPLETED_BOOKING_NOTIFICATION',
    driverCancelBooking: 'DRIVER_CANCEL_BOOKING_NOTIFICATION',
    userCancelBooking: 'USER_CANCEL_BOOKING_NOTIFICATION',
    userFinalCompleteBooking: 'USER_FINAL_COMPLETE_BOOKING_NOTIFICATION',
    adminAcceptBooking: 'ADMIN_ACCEPT_BOOKING_NOTIFICATION',
    adminCompletedBooking: 'ADMIN_COMPLETED_BOOKING_NOTIFICATION',
    adminCancelBooking: 'ADMIN_CANCEL_BOOKING_NOTIFICATION',
    newEventBookingNotification: 'NEW_EVENT_BOOKING_NOTIFICATION',
    tripAcceptedByAdminAssignYou: 'ADMIN_ACCERPT_BOOKING_AND_ASSIGN_DRIVER_NOTIFICATION',
    noDriverAvailableCancelBooking: 'NO_DRIVER_AVAILABLE_CANCEL_BOOKING_NOTIFICATION',
    tripStatusChange: 'TRIP_STATUS_CHANGED',
    chatSendToUser: 'CHAT_SEND_TO_USER',
    chatSendToDriver: 'CHAT_SEND_TO_DRIVER',
    chatSendDriverToDriver: 'CHAT_SEND_DRIVER_TO_DRIVER',
    default: 'DEFAULT'
  },
  socketType: {
    broadCast: 'BROAD_CAST',
    driver: 'DRIVER',
    user: 'USER',
    admin: 'ADMIN'
  },
  paymentMode: {
    cash: 'CASH',
    card: 'CARD',
    wallet: 'WALLET'
  },
  paymentStatus: {
    pending: 'PENDING',
    completed: 'COMPLETED'
  },
  tripType: {
    roundTrip: 'ROUNDTRIP',
    singleTrip: 'SINGLETRIP'
  },
  bookingStatus: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    COMPLETED: 'COMPLETED',
    ARRIVED: 'ARRIVED',
    STARTED: 'STARTED',
    ONGOING: 'ONGOING',
    CANCELED: 'CANCELED'
  },
  bookingStatusNumber: {
    PENDING: 1,
    ACCEPTED: 2,
    ARRIVED: 3,
    STARTED: 4,
    ONGOING: 5,
    COMPLETED: 6,
    CANCELED: 7
  },
  vehicleColors: [
    {
      color: "White",
      code: "#FFFFFF"
    },
    {
      color: "Silver",
      code: "#C0C0C0"
    },
    {
      color: "Black",
      code: "#000000"
    },
    {
      color: "Blue",
      code: "#0000FF"
    },
    {
      color: "Gray",
      code: "#808080"
    },
    {
      color: "Red",
      code: "#FF0000"
    },
    {
      color: "Green",
      code: "#008000"
    },
    {
      color: "Brown",
      code: "#A52A2A"
    },
    {
      color: "Gold",
      code: "#FFD700"
    },
    {
      color: "Metallic",
      code: "#D4AF37"
    },
    {
      color: "Yellow ",
      code: "#FFFF00"
    },
    {
      color: "Pink ",
      code: "#FFC0CB"
    },
    {
      color: "Orange ",
      code: "#FFA500"
    },
    {
      color: "Purple ",
      code: "#800080"
    }
  ],
  alreadyAcceptBookingStatus: 'This trip already accepted.',
  canceledBookingByUser: 'Trip canceled by customer.',
  vehicleNotFound: 'Vehicle no longer avaliable',
  serviceTypeNotFound: 'Service type no longer avaliable.',
  bothDriverPilot: 'Your partner is also pilot.',
  bothDriverCopilot: 'Your partner is also co-pilot.',
  backDateNotAllowed: 'Back date are not allowed.',
  driverHasNotVehicle: "You don't have vehicle.",
  driverAlreadyPaired: 'Driver is already paired.',
  driverAlreadyUnPaired: 'Driver is already un-paired.',
  unPairedFirst: 'First you un-paired then change the mode.',
  passwordResetLinkSendInYourEmail: 'Password reset link send to your trusted email Id.',
  emailNotFound: 'Email does not exists.',
  passwordChanged: 'Password changed successfully.',
  invalidPasswordResetToken: 'Invalid password reset token.',
  vehicleTypeNameAlreadyExists: 'Vehicle type name already exists.',
  serviceTypeNameAlreadyExists: 'Service type name already exists.',
  EventManagerNameAlreadyExists: 'Event Manager Name already exists',
  EventBookingNameAlreadyExists: 'Event Booking Name already exists',
  transmissionTypeNameAlreadyExists: 'Transmission type name already exists.',
  eventNameAlreadyExists: 'Event name already exists.',
  teamNameAlreadyExists: 'Team name already exists.',
  stateNameAlreadyExists: 'State name already exists.',
  cityNameAlreadyExists: 'ZipCode name already exists.',
  driverHasBusyOnBooking: 'You can not change the co-driver while a ride is ongoing.',
  notAllowedAcceptBooking: 'You are not allowed to accept the trip.',
  noLongerAvailable: 'This trip no longer available.',
  eventNoLongerAvailable: 'This event no longer available.',
  userAlreadyInAnotherTrip: 'User already on another trip.',
  alreadyChangedBookingStatus: 'This trip already assigned.',
  alreadyChangedEventBookingStatus: 'This event already status changed.',
  alreadyCanceledBookingStatus: 'This trip already canceled.',
  notAllowedCanceledBookingStatus: 'This trip is not canceled now.',
  deleted: 'Delted successfully.',
  blocked: 'Block successfully.',
  UnBlocked: 'Un-block successfully.',
  promoCodeExpired: 'Promo code already expired.',
  promoCodeAlreadyInUsed: 'Promo code already in used.',
  inValidPromoCode: 'Promo code is invalid.',
  promoOnlyCashbackOrPercentage: 'Please select only one of cashback, percentage',
  promoAlreadyExist: 'Promo code already exist',
  driverNotFoundInGivenArea: 'Driver not available in given area.',
  userBlocked: 'Your account has been blocked by admin.',
  emailAlreadyExist: 'Email already exists.',
  phoneAlreadyExist: 'Phone number already exists.',
  userNotFound: 'User does not exist.',
  eventManagerNotFound: 'Event Manager dose not exist',
  stripCardError: 'Error in strip customer creation',
  stripCardRetriveDataError: 'Error in fetching card data',
  InsufficientAmount: 'Insufficient amount to create booking.',
  errorInStripCardChargeAmount: 'Insufficient amount to create booking.',
  walletCharged: 'Your wallet successfully charged.',
  invalidStripCard: 'Invalid Card.',
  invalidUserCard: 'User card not find.',
  required: 'Please fill all required fields.',
  invalidReferral: 'Invalid referral code used.',
  referralCodeUsed: 'Referral code already in used.',
  minimumAmount: 'Enter the amount greater than or equal to 1$.',
  criticalVersion: 'Critical version must be less than latest version.',
  serverError: 'Internal Server Error',
  tokenExpire: 'Access denied.',
  unauthorizedRequest: 'Session has been expired.',
  tokenMissing: 'Token not found.',
  eventBookingNotFound: 'Event booking not found.',
  eventBookingNotEdit: 'Event booking not edit at this moment.',
  eventBookingNotCancel: 'Event booking not cancel at this moment.',
  driverNotFound: 'Driver not found.',
  driverLocationUpdate: 'Driver location update successfully.',
  userAlreadyExist: 'User already exists.',
  eventManagerAlreadyExist: 'Event Manager already exists',
  eventBookingAlreadyExist: 'Event Booking already exists',
  verificationCodeSendInEmail: 'A message with a verification code has been sent to your trusted email Id.',
  verificationCodeSendInPhone: 'A message with a verification code has been sent to your trusted phone number.',
  sendSMSforTip: 'A Sms with a link has been sent to your mobile number for tip',
  driverAlreadyExist: 'Driver already exists.',
  invalidPassword: 'Password is invalid.',
  productImage: 'static/product',
  bannerImage: 'static/banner',
  subCategoryImage: 'static/subCategory',
  driverDocumentImage: 'static/driverDocument',
  categoryImage: 'static/category',
  driverImage: 'static/driver',
  driverJobImage: 'static/driverJobCompleted',
  brandImage: 'static/brand',
  userImage: 'static/user',
  serviceTypeImage: 'static/serviceType',
  recordExists: 'Record already exists.',
  onForgotPassword: 'A reset password link is sent to your email successfully!',
  invalidPromo: 'Invalid promo code.',
  promoExpired: 'This promo code is expired.',
  promoAlreadyUser: 'This promo code is already used.',
  placeOrder: 'Order placed successfully!',
  tryLater: 'Please try later.',
  verifyOtp: 'Your OTP is verified',
  otpError: 'Please enter the valid Wingmen code.',
  driverRegister: 'You are register as a driver but not verified from admin',
  notRegisterAsDriver: 'Something is missing not register as driver',
  aproveDriver: 'You are aprove by the admin',
  unAproveDriver: 'You are unaprove by the admin',
  passwordNotMatch: 'Password is incorrect.',
  samePasswordNotAllowed: 'Same password not allowed.',
  login: 'Your phone number and password is match',
  update: 'Your data will be updated',
  nearByDriver: 'Your near by driver is found',
  driverNotFount: 'Driver not found in your current location',
  enterValidId: 'Please enter the valid ID',
  TRUE: 'true',
  FALSE: 'false',
  otpSuccessfully: 'OTP successfully genrated.',
  register: 'Your phone no is already register',
  ValidId: 'Please enter the valid id',
  driverHaveNoCar: 'Your driver have no car ',
  driverIsAlreadyAssign: 'Driver is alreday assign',
  autoReviewForDriver: 'No review for now.',
  autoReview:"You have a pending review.",
  reviewDone: "Thanks for responding immediately",
  reviewSkip: "Review skip.",
  notFound: "You are not a Pilot or Co-Pilot in this ride",
  driverRemove: "You have been removed as a Pilot in this ride",
  CodriverRemove: "You have been removed as a Co-Pilot in this ride",
  sendSMSforConfirmation48: "Reminder at 48 hours before Scheduled Ride",
  sendSMSforConfirmation24: "Reminder at 24 hours before Scheduled Ride",
  sendSMSforConfirmation6: "Reminder at 6 hours before Scheduled Ride",
};
